version: '3.8'

services:
  express-api:
    build: ./app
    container_name: express-api
    ports:
      - "3000:3000"
    volumes:
      - ./app/data:/app/data    
    networks:
      - wso2-network

  wso2-api:
    image: wso2/wso2am:latest
    container_name: wso2-api
    platform: linux/amd64
    ports:
      - "9443:9443"   
      - "8243:8243"   
      - "8280:8280"  
    environment:
      - WSO2_ADMIN_USERNAME=admin
      - WSO2_ADMIN_PASSWORD=password
      - JAVA_OPTS=-Dsetup -Dadmin.role=Internal/publisher,Internal/creator,Internal/subscriber
    depends_on:
      - express-api
    volumes:
      - wso2_repository:/home/wso2carbon/wso2am-4.2.0/repository   
      - wso2_logs:/home/wso2carbon/wso2am-4.2.0/repository/logs    
    networks:
      - wso2-network

  wso2-db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: apim_db
      MYSQL_USER: wso2
      MYSQL_PASSWORD: wso2
    volumes:
      - wso2_mysql:/var/lib/mysql
    networks:
        - wso2-network


networks:
  wso2-network:
    driver: bridge

volumes:
  wso2_repository:
  wso2_logs:
